on:
  schedule:
    - cron: '0 1 * * *'
  workflow_dispatch:
  workflow_call:

jobs:
  sonarcloud:
    name: Run Tests and SonarCloud Scan
    if: ${{ github.event_name != 'schedule' && github.actor != 'dependabot[bot]' }}
    runs-on: ubuntu-latest
    steps:
      - name: Check out code
        uses: actions/checkout@v6
        with:
          fetch-depth: 1

      - name: Setup Node.js
        uses: actions/setup-node@v6
        with:
          node-version-file: .nvmrc

      - name: Test code and Create Test Coverage Reports
        run: |
          mkdir -p coverage
          chmod -R a+rw ./coverage
          npm ci
          npm run test

      - name: SonarCloud Scan
        uses: SonarSource/sonarqube-scan-action@v6
        env:
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}

  trivy-scan:
    name: Trivy Vulnerability Scan
    runs-on: ubuntu-latest
    steps:
      - name: Check out code
        uses: actions/checkout@v6
        with:
          fetch-depth: 1

      - name: Setup Node.js
        uses: actions/setup-node@v6
        with:
          node-version: '24.x'

      - name: Check lockfile is up to date
        run: npm ci

      - name: Run Aqua Trivy scan
        id: trivy-scan
        uses: aquasecurity/trivy-action@0.33.1
        with:
          scan-ref: .
          scan-type: repository
          format: table
          exit-code: 1
          trivyignores: .trivyignore
          severity: CRITICAL,HIGH,MEDIUM,LOW
          limit-severities-for-sarif: true
        continue-on-error: true
        env:
          TRIVY_INCLUDE_DEV_DEPS: 'true'

      - name: Fail if vulnerabilities found
        if: ${{ steps.trivy-scan.outcome == 'failure' }}
        run: exit 1

  unpinned-dependencies:
    name: Check for Unpinned NPM Dependencies
    runs-on: ubuntu-latest
    steps:
      - name: Check out code
        uses: actions/checkout@v6
        with:
          fetch-depth: 1

      - name: Check for unpinned NPM dependencies
        run: |
          chmod +x ./scripts/check-unpinned-dependencies.sh
          ./scripts/check-unpinned-dependencies.sh
